AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Demo to explore how the PowerShell custom runtime and a Lambda function work.
##########################################################################
#  Parameters & Globals                                                  #
##########################################################################
Globals:
  Function:
    Tracing: Active
    Tags:
      Application: demo-runtime-layer-function
Resources:
##########################################################################
#  Lambda functions                                                      #
##########################################################################
  DemoPowerShellFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: PowerShell-Lambda-Runtime Demo Function
      CodeUri: function/
      Runtime: provided.al2
      Architectures: [ arm64 ]
      Handler: examplehandler.ps1::handler
      MemorySize: 1024
      Timeout: 100
      Layers:
        - !Ref PwshArm64RuntimeLayer
        - !Ref DemoAWSToolsLayer
    Metadata:
      BuildMethod: makefile
##########################################################################
#  Lambda layers                                                         #
##########################################################################
  PwshArm64RuntimeLayer: 
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Lambda Layer containing PowerShell
      ContentUri: ../../powershell-runtime-arm64
      CompatibleRuntimes:
        - provided.al2
      CompatibleArchitectures:
        - arm64
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  DemoPwshArm64RuntimeParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: demo-lambda-powershell-runtime-arm64-latest-version-arn
      Description: PwshRuntime Layer Name
      Type: String
      Value: !Ref PwshArm64RuntimeLayer

  DemoAWSToolsLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      Description: Layer containing Demo-AWS.Tools
      ContentUri: ../../powershell-modules/AWSToolsforPowerShell/Demo-AWS.Tools
      CompatibleRuntimes:
        - provided.al2
      CompatibleArchitectures:
        - x86_64
        - arm64     
      RetentionPolicy: Delete
    Metadata:
      BuildMethod: makefile
  DemoAWSToolsParameter:
    Type: AWS::SSM::Parameter
    Properties:
      Name: lambda-powershell-DemoAWSTools-latest-version-arn
      Description: DemoAWSTools Layer Name
      Type: String
      Value: !Ref DemoAWSToolsLayer

##########################################################################
#  OUTPUTS                                                               #
##########################################################################
Outputs:
  PwshRuntimeLayer:
    Value: !Ref PwshArm64RuntimeLayer
    Description: PwshRuntimeLayer Layer ARN
  DemoAWSToolsLayer:
    Value: !Ref DemoAWSToolsLayer
    Description: DemoAWSToolsLayer Layer ARN    
  DemoPowerShellFunction:
    Value: !Ref DemoPowerShellFunction
    Description: PowerShell Lambda Function
